name: solutions_itd_mobile
description: Solutions ID - mobile
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.19.3 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    flutter_localizations:
        sdk: flutter
    provider: ^6.0.5
    connectivity: ^3.0.6
    device_info: ^2.0.3
    shared_preferences: ^2.0.18
    uuid: ^3.0.7
    loading_animation_widget: ^1.2.0+4
    auth0_flutter: ^1.1.0
    flutter_dotenv: ^5.0.2
    http: ^0.13.5
    fluttertoast: ^8.2.1
    get: ^4.6.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.1
    build_runner: ^2.3.3
    flutter_launcher_icons: "^0.12.0"

flutter:
    assets:
        - assets/example_app_icon.png
        - assets/logo_solutions_itd_small.png
        - assets/logo_solutions_itd.png
        - assets/only_logo.png
        - assets/example_business_logo.png
        - .env
    generate: true
    uses-material-design: true

flutter_icons:
    android: "launcher_icon"
    ios: true
    remove_alpha_ios: true
    image_path: "assets/only_logo.png"
    min_sdk_android: 21
    web:
        generate: true
        image_path: "assets/only_logo.png"
        background_color: "#ffffff"
        theme_color: "#ffffff"
    windows:
        generate: true
        image_path: "assets/only_logo.png"
        icon_size: 256
    macos:
        generate: true
        image_path: "assets/only_logo.png"
